name: test-cafe
on: workflow_dispatch
jobs:
  test-cafe-run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - name: Run tests
        run: npm run codeceptjs
      - name: GitHub Commit & Push
        if: ${{ always() }}
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          message: "Updating test report"
          branch: "main"
